ansible_become_pass: ENC[AES256_GCM,data:0lO/9d0=,iv:X0kMr0z1fwejxdRbvbxC0F8lgbPB2FIaeafkDsyqJM8=,tag:TWLrFPZq6kbBY5iaQoIOBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vrnjen6tmn6p56wthz7cyl43rsp9z8k8lwn2u8gcn9w89h703sq34ezrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSXp3ekxrRnRtWE9JT1NM
            QjZyWFIwZVBBcmd5N0dpd1VoQ3BsSlp4amtRCkV1NHo4VzlEU0t6M2FieEpvMFpz
            eDdsUXMzdzlhT2p4Mno1RHFUWUJzZ0EKLS0tIEhZVDRUTVBFdG5jT2JwclphZlNv
            NnQ2N3BEclNYVy82TmNjVEFwZVEyQ00KHteDIjS8GcfF22dZUZSZ6ObPasOsZEB3
            XWwlGq3NoQ9s5FstTxg4nanw0NEwI58Mvtw+lboFrr7k8tCOUMmlhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T14:03:29Z"
    mac: ENC[AES256_GCM,data:koc0rl1SGsHDLM9DNj6TVRD+xT09doSbO5uSQDcqAgOZf9pgCBi0PGtXzj/pr7yjy/eBGaNpqb/EufPjWCw2gMd3nsaSy5l0t+UcONBLNSjJmdL5kqCS97VbsKbhrCGWGsIshaKKQHkQGP3aXKvFNNRIMMbmGsUhR8ipIWudHAQ=,iv:83/NzYlv6pXpT1b3cooovmf8uPS1hksk1AJfiYrSJTs=,tag:keB3S1itT+xkvLDb24GSvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
