apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vrnjen6tmn6p56wthz7cyl43rsp9z8k8lwn2u8gcn9w89h703sq34ezrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ3F3MjJJd1NMTFhTenVR
            R1gxLzJQNG8za01CRENtM3FTQzcrNEdVZVM4CmtVbXUzajlyV0lYTlpXY3VMMWNL
            ZXpsaWY1cmV0eEZkSEJ2aTZjWWFlUlkKLS0tIEE4aXlLV3kzVkEyN3dMU0xacm85
            MnhBV0dJdGswS0RNT2gvclZBMDRNSU0K/RF0RLUe1Tb77RXj9W+dILBgGTZ5nL1O
            6XIc8EU0O2wGBt21tMkBsHVq6YaXl98xT9PGTZmMpkEmLWmzrmEhoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T14:04:27Z"
    mac: ENC[AES256_GCM,data:BC6SAEz2F4fZDEE0JTDSSSLBRoPJv2egyikVEGxf3eKTYFYqks3h3NPZXaVWW4I+LAY8IMmZ9ELPTF0bKvaJ0aQfjkO9So2YAty/w3cPBvQgzyT3p5BVc2B2pPwv73MwQ74MXlXCmanwbi2pCymPeus4LLB8HZcdmn6UfqdeYYk=,iv:hfpth2mKC3SGW5vWduDQ6Ao7icZLy74h9a8h9Pcl1Pc=,tag:W2dgD6fUoZtGk3Sik9BFjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
