apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:+Qd/PKQow/xEbuR/FpCyL//e57IqwZzNCBnzti53jlOuAPr+RhS63Q==,iv:ntL2MhReAubnZGm/240X5ZOQJgvMAz4DiHGNLK06fys=,tag:4DjBmkAh7CV4uJT49MsQyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vrnjen6tmn6p56wthz7cyl43rsp9z8k8lwn2u8gcn9w89h703sq34ezrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNjkyTFEvZERnSW5CbWpC
            alZtcWhwQ1JWMSswajNYVUJyeXh2SG5wK1FNCkNtejJFU1FOWUM0d3UwS0JnckZq
            U2dIaDFFVlVPcFRUMmxVSWRkTTN5OXcKLS0tIDJhTmJxQ0RKbTViZXRTajJGa2dJ
            NncwUkkwNjREZHVTRGUraTdDWnJ1eU0KhjVcSQv6/hfLsdvpUEhPtQyyLAmj7Sfw
            HQU9jpLI0HjEondjZPcIxTIYKe1HM4/B6+eGr35XQoj+mYrFk3POVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T14:04:27Z"
    mac: ENC[AES256_GCM,data:KI0X7Hn19migiTp81dAFmUTiiG6NnPfTDFCT+rOUprB9OUlLi3Y78Ciu3NAzT34QmwSMsCcwu4wbvtw3UAIhJFbm0uk3B9SaDq1HnQMgaCBQ2ocnJWletjuydPINb4+dikeGDcYTvo7wMnI7IixoP9BWWAOHEYy0ssUAQp/62u4=,iv:yTS2LotYhY80k+knOPZkcAoEpXV3TFSpUi9z1WJ0RwQ=,tag:HUcV4JZS6oZVVqdWPMD6TA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
