apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:fzu3LkxiuqZW2BnwmkA2sEAMmEt0xFyVUsiHYom+YbvBT6bW+4vklA==,iv:RreOY0Ir7NjeIKGmm8ElXBdTe0LJ/ZNv4fojBsYhXqg=,tag:koNm+iBD8rkwyM6kbeAuRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vrnjen6tmn6p56wthz7cyl43rsp9z8k8lwn2u8gcn9w89h703sq34ezrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YlpjSEhzUVBPWkpMSndr
            TlBLSlozME5zanlKQkpkdTNueEtoK2ZwVm5NClozdVQvMWhLSmN0cjhQMDRpYk8y
            V3JaR2g0Sm5lZmY2bzVBQm1HUnRHZTAKLS0tIEhtQjVFUVZLSUtiWjlxWHJYcldI
            SHBXck5IdVVUR05TWUx6RVRXcGNhR0EKIZpQI7mTeRaBC+IMZ2wTLSQy+QYhcCwl
            omnzFeroEgY1i/DvzaE07s8fjNvBJLtcNmJtvDxLFrlrLwQB0ZorMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T14:04:28Z"
    mac: ENC[AES256_GCM,data:TzBwVRZKSLATJ3OBi/ScZW3Dh2WNI5bPYswDHatwZICTs0Eu6oc+YmFMcZs7AbRl3Gc3UWfc57B6NImIfgBHdrHfK2J5fZkPC536TSYZ4ET6i9RAeSXSi1FA+t6ndHPZ9r5tNswqhLikblyYobq4MzBh7X2qrFBy05UYUX+rkaQ=,iv:+Tj29kcMlSDGDrjgHbZPpTewroEzVfAsAt/9git7R5M=,tag:W60xVPrbUvzAqW9GDPu6Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
