apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:n/wUA/eDby2xynh+g3NO+h3HFsAa0CmW0tMKwNTVmZD3ndbmtZeGNg==,iv:PsKIBejCynplsILmzDxTR3uzT0TKJvs5cpBJm5PLDaU=,tag:dj3OXV8hpUHi+bVav0N8/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fl7877saxjya7mue72llx4ux6ufv7qdc3tgzpzfdsmsplk067pyqyf7p05
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMitoSUEvVVY1WUsrcStD
            VEdPWjdPYmhJdXhaTXN6L0hBSDZUdGpGSFFFCjEyMUE1N2hXcVFvQkcwNEh0ZjVl
            bUxOdDRuL0xRb0lhajdMMVBMUVBUMW8KLS0tIG5SUWdSSjdna3B1a0RpTlppL1FJ
            UGpWWDNJRlBESVh0RUhRL3A5bE9jS0EKT/eT9gUmy3s/Ip2JjzDKGaD0NakV8Z2w
            z4blt1bn5upkW+LI9Q7I/+xvpT+a7N9fbygVz0UAoSzH7914i6J61Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T17:35:47Z"
    mac: ENC[AES256_GCM,data:1p7pArkFD/vfXTqhmLyJVhNFNM+C9QgzRGe+Oba5NDKd/Dptu8A4PdcQK6B/ZniuLaGlhduyLSBchQBdEa26KCgJ7o7vxyk60eg/Qf6z0OXDbvlj+FZzx39ybOjLZy0D+8fhXruunig/cWeNtsz0/RplPBbDe1kLoafWjgCJ8fU=,iv:8M0I+FWD07QbHYIDYSW7guHqgSa8MxQp9D0hgnUcYp8=,tag:Oko/Yt5/fEqn1NNqRVmwEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
