apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0fSERW2/Id5w/IzphwkNerGUYakWH8nlyEbLDE5KjqAw091j,iv:HE5rJzFT4j5QSbqVJapATGmxDDBuvyxyzxQIkZ2We64=,tag:RjqM2KwZf1JUm5eWkrqO0g==,type:str]
    credentials.json: ENC[AES256_GCM,data:Lk0W4nv+4qlIE++rFYNghPrIpLiqWSLqEKv8qv6adLAo0k008zBUkfDZlVk23f1fXzOt6A7fW4iwvBo7NkHbD9mwEtN2ImnW2hNT+W0jUsfH6O06n4MeIYOXZ03n3GRhG7CRn2FTlziEt1r+T+XR4Fru3Wl7GEM+J7t5p1NoLDD+AS6fBgyL9ZPonzmQP01zknGAfSMykcZPW1oiDl1qI76VDtO3/slpx5eBt2g8TQ==,iv:vWrdOvug7TPIpaqyQxuHQa0P7ETIe45pNY/WLPn5btA=,tag:2mNw/m/whxs0lGy2d9AaOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vrnjen6tmn6p56wthz7cyl43rsp9z8k8lwn2u8gcn9w89h703sq34ezrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbzBZZEdNbHlBaUFuV25E
            bWxYdVRFRms5VnBlZERmSXRieFZhY0MrQzJVCnpyZnY3ZmpWd2huSzkxREgzd2Ji
            dFRscUFDeS82LzVzZkQ5a2JVVmc2ZzgKLS0tIEFSZDI4RTdnVFJONC9nSXhuRnNQ
            ZUZSeEdUTXduNHVLdWY0cXZBMzg3bUUKe6YQT6s9CsPlZ6/FKKaGWOiPkaUv3v9T
            wirkui4y9Ibi4BNy76rWCx1dMzSERXQvu2PnnWnvIytRCOL+Ya0y2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T14:04:28Z"
    mac: ENC[AES256_GCM,data:XUA/WQVm34qaoYJM6tokeIfaWgthi8fY02geNCdoML924xU3wE1FRUfXZUzv0XSKW4Tv6tfhKPSAURD4RJ2PMPvxexccejmI7oK56WutHGOdPckhzsF56S3r0AcF1kH48Dy0F0bUX5fo6FAUcsAGiVay3XO4HIAxQi0odvF30zA=,iv:4rOnUbegDXxidfnF5iimONnzMXkeHfZzQEpyv9UpZ/8=,tag:/oWHYNb4QToaBPjKzIq9Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
